# Generated by Django 4.0 on 2023-03-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_listing_brand_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='transimission',
            new_name='transmission',
        ),
    ]
